gvot/urls.py
from django.conf import settings
from django.urls import include, path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from .base import views

urlpatterns = [
    # Wagtail's applications
    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    # Local applications
    path('docs/', include('docs.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.views import defaults as default_views

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request,
             kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied,
             kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found,
             kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns.insert(0, path('__debug__/', include(debug_toolbar.urls)))

# Root application
urlpatterns += [
    path('<uuid:uuid>/', views.RootUUID.as_view(), name='uuid'),
    path('', include(wagtail_urls)),
]

gvot/base/forms.py
import csv

from django import forms
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

from .models import EmailTemplate, Scrutin


class MaillingForm(forms.Form):
    """
    Formulaire pour les emailings.
    """

    template = forms.ModelChoiceField(
        queryset=EmailTemplate.objects,
        empty_label="Sélectionnez un modèle",
    )

    dests = forms.ChoiceField(
        choices=[
            (None, "Sélectionnez les destinataires"),
            ('tous', "Tous les participants"),
            ('exprimes', "Tous les participants ayant voté"),
            ('abstenus', "Tous les participants n'ayant pas encore voté"),
        ],
    )

    filter_key = forms.ChoiceField(
        choices=(),
        required=False,
    )

    filter_ope = forms.ChoiceField(
        choices=(
            (None, "Choississez une opération de filtrage"),
            ('icontains', "Contient"),
            ('istartswith', "Commence par"),
            ('iendswith', "Termine par"),
            ('iexact', "Est"),
            ('not_isempty', "Est défini"),
            ('not_icontains', "Est défini et ne contient pas"),
            ('not_istartswith', "Est défini et ne commence pas par"),
            ('not_iendswith', "Est défini et ne termine pas par"),
            ('not_iexact', "Est défini et est différent de"),
            ('isempty', "N'est pas défini"),
            ('empty_not_icontains', "N'est pas défini ou ne contient pas"),
            (
                'empty_not_istartswith',
                "N'est pas défini ou ne commence pas par",
            ),
            ('empty_not_iendswith', "N'est pas défini ou ne termine pas par"),
            ('empty_not_iexact', "N'est pas défini ou est différent de"),
        ),
        required=False,
    )

    filter_val = forms.CharField(
        required=False,
        max_length=255,
    )

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('filter_key') and not cleaned_data.get(
            'filter_ope'
        ):
            self.add_error(
                'filter_ope',
                ValidationError(
                    "Veuillez définir l'opération de filtrage à appliquer"
                ),
            )
        if cleaned_data.get('filter_ope') and not cleaned_data.get(
            'filter_key'
        ):
            self.add_error(
                'filter_key',
                ValidationError(
                    "Veuillez définir à quel champ s'applique le filtre"
                ),
            )
        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # We dynamically override the choices to build a grouped select
        self.fields['template'].choices = [
            (None, self.fields['template'].empty_label)
        ] + [
            (
                scrutin.title,
                [
                    (tpl.id, "{} : {}".format(scrutin, tpl.nom))
                    for tpl in scrutin.emailtemplate_set.spammable()
                ],
            )
            for scrutin in Scrutin.objects.live().public()
        ]

        self.fields['filter_key'].choices = [
            (None, "Filtrez selon un champ personnalisé")
        ] + [
            (
                scrutin.title,
                [
                    (chp, "{} : {}".format(scrutin, chp))
                    for chp in scrutin.pouvoirs_champs_persos()
                ],
            )
            for scrutin in Scrutin.objects.live().public()
        ]


class MaillingSingleForm(forms.Form):
    """
    Formulaire pour renvoyer les infos d'un pouvoir.
    """

    def __init__(self, *args, pouvoir=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields[
            'template'
        ].queryset = pouvoir.scrutin.emailtemplate_set.spammable()

    template = forms.ModelChoiceField(
        queryset=EmailTemplate.objects,
        empty_label="Sélectionnez un modèle",
    )


class ImportForm(forms.Form):
    """
    Formulaire pour les imports CSV des pouvoirs.
    """

    scrutin = forms.ModelChoiceField(
        queryset=Scrutin.objects,
        empty_label="Sélectionnez un scrutin",
        help_text="Les pouvoirs importés ne seront associés qu'à ce scrutin.",
    )

    remplace = forms.BooleanField(
        label="Import hégémonique",
        help_text=(
            "Si coché, tous les pouvoirs existants lié au scrutin sélectionné "
            "seront détruits et/ou remplacés par l'importation."
        ),
        required=False,
    )

    csv_file = forms.FileField(
        help_text=mark_safe(
            "Fichier au format csv dans un codage utf-8 ; "
            "séparateur : « , » ; délimiteur de texte : « \" » (doubles "
            "quotes).<br>Colonnes attendues : « nom{star} », "
            "« prenom{star} », « collectif{star} », "
            "« courriel{star}{star} », « contact » et « ponderation ».<br>"
            "Au moins un colonne marquée par « {star} » doit être remplie.<br>"
            "Les colonnes marquée par « {star}{star} » ne peuvent être vides."
            "<br>Une pondération absente sera interprétée à la valeur "
            "« 1 ».".format(star='<span style="color:#cd3238">*</span>')
        ),
    )

    def clean_csv_file(self):
        csv_file = self.files['csv_file']
        csv_file.seek(0)  # rewind probably needed
        if csv_file.multiple_chunks():
            raise ValidationError(
                "Votre fichier est trop énorme. La limite est fixée à 2,5Mo."
            )
        try:
            decoded_file = csv_file.read().decode('utf-8').splitlines()
        except Exception as e:
            raise ValidationError(
                "Impossible de décoder votre fichier : {}".format(e)
            )
        try:
            reader = csv.reader(decoded_file)
            header = [s.strip() for s in reader.__next__()]
        except Exception:
            raise ValidationError(
                "Impossible de lire des données CSV dans ce fichier."
            )

        if not {'nom', 'prenom', 'courriel'}.issubset(set(header)):
            raise ValidationError(
                "Impossible de trouver les bonnes colonnes dans le fichier. "
                "Colonnes trouvées : {}.".format(
                    ", ".join(["« {} »".format(c) for c in header])
                )
            )


class AnswerForm(forms.Form):
    """
    Formulaire pour répondre à un participant.
    """

    reply_to = forms.EmailField(
        label="De",
        help_text="Une adresse email valide qui permettra "
        "une éventuelle réponse de la personne.",
    )
    message = forms.CharField(
        widget=forms.widgets.Textarea, label="Votre message"
    )

gvot/templates/import/confirm.html
{% extends "modeladmin/create.html" %}
{% load static accessors modeladmin_tags %}

{% block titletag %}Importer des pouvoirs (2/2){% endblock %}

{% block content %}
  {% include "wagtailadmin/shared/header.html" with title="Importer des pouvoirs" icon="download" subtitle=" Analyse de l'import avant validation" %}

<div class="nice-padding">
  <div class="overflow">

    {% if import_ko %}
      <div class="help-block help-critical">
        <h2>Ligne{{ import_ko | pluralize }} nécessitant correction{{ import_ko | pluralize }}</h2>
      </div>
      <table class="listing">
        <thead>
          <tr>
            {% for field in basic_fields %}
              {% if forloop.first %}
                <th id="{{ field }}" class="ordered ascending">
                  {{ field | title }}
                </th>
              {% else %}
                <th id="{{ field }}">
                  {{ model | verbose_fieldname:field | title }}
                </th>
              {% endif %}
            {% endfor %}
            {% with field="courriels" %}
              <th id="{{ field | slugify }}">
                {{ field | title }}
              </th>
            {% endwith %}
            {% for field in extended_fields %}
              <th id="{{ field | slugify }}">
                {{ field | title }}
              </th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for index, pouvoir, exception in import_ko %}
            <tr>
              {% for field in basic_fields %}
                <td>
                  {% if forloop.first %}
                    {{ index | add:2 }}
                  {% else %}
                    {{ pouvoir | getattr:field | default_if_none:'-' | truncatechars:100 }}
                    {% for error in exception.error_dict|get:field %}
                      {% for message in error.messages %}
                        <p class="error-message">
                          {{ message }}
                        </p>
                      {% endfor %}
                    {% endfor %}
                    {% if field == 'nom' %}
                      {% for error in exception.error_dict|get:'__all__' %}
                        {% for message in error.messages %}
                          <p class="error-message">
                            {{ message }}
                          </p>
                        {% endfor %}
                      {% endfor %}
                    {% endif %}
                  {% endif %}
                </td>
              {% endfor %}
              {% with field="courriels_list" %}
                <td>
                  {{ pouvoir.courriels_list|join:", " | default_if_none:'-' | truncatechars:100 }}
                  {% for error in exception.error_dict|get:"courriel" %}
                    {% for message in error.messages %}
                      <p class="error-message">
                        {{ message }}
                      </p>
                    {% endfor %}
                  {% endfor %}
                </td>
              {% endwith %}
              {% for field in extended_fields %}
                <td>
                  {{ pouvoir | get_champ_perso:field | default_if_none:'-' | truncatechars:100 }}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}

    {% if import_warn %}
      <div class="help-block help-warning">
        <h2>Ligne{{ import_warn | pluralize }} nécessitant attention</h2>
      </div>
      <table class="listing">
        <thead>
          <tr>
            {% for field in basic_fields %}
              {% if forloop.first %}
                <th id="{{ field }}" class="ordered ascending">
                  {{ field | title }}
                </th>
                <th id="warnings">
                  Avertissements
                </th>
              {% else %}
                <th id="{{ field }}">
                  {{ model | verbose_fieldname:field | title }}
                </th>
              {% endif %}
            {% endfor %}
            {% with field="courriels" %}
              <th id="{{ field | slugify }}">
                {{ field | title }}
              </th>
            {% endwith %}
            {% for field in extended_fields %}
              <th id="{{ field | slugify }}">
                {{ field | title }}
              </th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for index, pouvoir, warning in import_warn %}
            <tr>
              {% for field in basic_fields %}
                <td>
                  {% if forloop.first %}
                    {{ index | add:2 }}
                </td>
                <td>
                      <p class="error-message">
                        {{ warning }}
                      </p>
                  {% else %}
                    {{ pouvoir | getattr:field | default_if_none:'-' | truncatechars:100 }}
                  {% endif %}
                </td>
              {% endfor %}
              {% with field="courriels_list" %}
                <td>
                  {{ pouvoir.courriels_list|join:", " | default_if_none:'-' | truncatechars:100 }}
                </td>
              {% endwith %}
              {% for field in extended_fields %}
                <td>
                  {{ pouvoir | get_champ_perso:field | default_if_none:'-' | truncatechars:100 }}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}

    {% if import_ok %}
      <div class="help-block help-info">
        <h2>Ligne{{ import_ok | pluralize }} importable{{ import_ok | pluralize }}</h2>
      </div>
      <table class="listing">
        <thead>
          <tr>
            {% for field in basic_fields %}
              {% if forloop.first %}
                <th id="{{ field }}" class="ordered ascending">
                  {{ field | title }}
                </th>
              {% else %}
                <th id="{{ field }}">
                  {{ model | verbose_fieldname:field | default_if_none:'-' | title }}
                </th>
              {% endif %}
            {% endfor %}
            {% with field="courriels" %}
              <th id="{{ field | slugify }}">
                {{ field | title }}
              </th>
            {% endwith %}
            {% for field in extended_fields %}
              <th id="{{ field | slugify }}">
                {{ field | title }}
              </th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for index, pouvoir, _ in import_ok %}
            <tr>
              {% for field in basic_fields %}
                <td>
                  {% if forloop.first %}
                    {{ index | add:2 }}
                  {% else %}
                    {{ pouvoir | getattr:field | default_if_none:'-' }}
                  {% endif %}
                </td>
              {% endfor %}
              {% with field="courriels_list" %}
                <td>
                  {{ pouvoir.courriels_list|join:", " | default_if_none:'-' | truncatechars:100 }}
                </td>
              {% endwith %}
              {% for field in extended_fields %}
                <td>
                  {{ pouvoir | get_champ_perso:field | default_if_none:'-' | truncatechars:100 }}
                </td>
              {% endfor %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% endif %}
  </div>
</div>

{% include "includes/confirm_button.html" with preposition="d'" msg="Effectuer l'import" %}

{% endblock %}

gvot/templates/import/index.html
{% extends "modeladmin/create.html" %}
{% load static %}

{% block titletag %}Importer des pouvoirs (1/2){% endblock %}

{% block header %}
  {% include "wagtailadmin/shared/header.html" with title="Importer des pouvoirs" icon="download" subtitle=" Une page de confirmation vous sera soumise avant l'importation effective des données." %}
{% endblock %}

{% block form_action %}{% endblock %}

{% block form %}
  <ul class="objects">
    <li class="object required model_choice_field">
      <div class="title-wrapper">
        <label for="id_scrutin">
          Scrutin
        </label>
      </div>
      <div class="object-layout">
        <div class="object-layout_big-part">
          <fieldset>
            {% include "wagtailadmin/shared/field_as_li.html" with field=form.scrutin show_label=False  %}
          </fieldset>
        </div>
      </div>
    </li>
    <li class="object boolean_field">
      <div class="object-layout">
        <div class="object-layout_big-part">
          <fieldset>
            {% include "wagtailadmin/shared/field_as_li.html" with field=form.remplace show_label=True  %}
          </fieldset>
        </div>
      </div>
    </li>
    <li class="object required file_field">
      <div class="title-wrapper">
        <label for="id_csv_file">
          Fichier CSV
        </label>
      </div>
      <div class="object-layout">
        <div class="object-layout_big-part">
          <fieldset>
            {% include "wagtailadmin/shared/field_as_li.html" with field=form.csv_file show_label=False  %}
            <p>
              Un exemple d'un tel fichier est <a href="{% static '/files/exemple_import_pouvoir.csv' %}">fourni ici</a>.
            </p>
          </fieldset>
        </div>
      </div>
    </li>
  </ul>
{% endblock %}

{% block form_actions %}
  <div class="dropdown dropup dropdown-button match-width">
    <button type="submit" class="button action-save button-longrunning" data-clicked-text="Poursuivre">
      <span class="icon icon-spinner"></span><em>Poursuivre</em>
    </button>
  </div>
{% endblock %}